name: Feature request
description: Describe the feature you would like to have
title: "[Feature]: "
labels: [ "enhancement", "to refine" ]
body:
  - type: input
    id: feature-request-problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: input
    id: feature-request-solution
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: input
    id: feature-request-alternatives
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: feature-request-additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
